In [1]:
import tensorflow as tf

### Variables

Variables are tensors with fixed type and shape but their values can be changed through operations.

In [2]:
x = tf.constant([[1.0, 2.0]])

In [3]:
x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

We can create a variable from a tensor by calling `tf.Variable`

In [4]:
x_var = tf.Variable(x)

tf.Variable share attributes with tensors

In [5]:
x_var.shape

TensorShape([1, 2])

In [6]:
x_var.numpy()

array([[1., 2.]], dtype=float32)

### Gradient

`tf.Variable` allow us to calculate gradients

In [7]:
x = tf.Variable([[1.0, 2.0]])
# tf.Variable([[1.0,2.0]]) creates a 1x2 tensor
# this tensor can be understood as an equation of:
# y = 1*x1 + 2*x2

We use the `tf.GradientTape` api to calculate the gradient of a function

In [8]:
with tf.GradientTape() as tape:
    # y = x**2 computes the square of each element of x
    y = x**2

    # tape.gradient(y, x) calculates the gradient of y with respect to x
    # mathematically, dy/dx = 2*x
    # dy/dx1 = 2*x1 = 2*1 = 2
    # dy/dx2 = 2*x2 = 2*2 = 4
    dy_dx = tape.gradient(y, x)

In [9]:
dy_dx.numpy()

array([[2., 4.]], dtype=float32)